&disasm_00, /* 0x00 */
&disasm_01, /* 0x01 */
&disasm_02, /* 0x02 */
&disasm_03, /* 0x03 */
&disasm_04, /* 0x04 */
&disasm_05, /* 0x05 */
&disasm_unknown, /* 0x06 */
&disasm_unknown, /* 0x07 */
&disasm_unknown, /* 0x08 */
&disasm_unknown, /* 0x09 */
&disasm_unknown, /* 0x0A */
&disasm_unknown, /* 0x0B */
&disasm_unknown, /* 0x0C */
&disasm_unknown, /* 0x0D */
&disasm_unknown, /* 0x0E */
&disasm_unknown, /* 0x0F */
&disasm_10, /* 0x10 */
&disasm_11, /* 0x11 */
&disasm_12, /* 0x12 */
&disasm_13, /* 0x13 */
&disasm_14, /* 0x14 */
&disasm_15, /* 0x15 */
&disasm_16, /* 0x16 */
&disasm_17, /* 0x17 */
&disasm_18, /* 0x18 */
&disasm_19, /* 0x19 */
&disasm_unknown, /* 0x1A */
&disasm_unknown, /* 0x1B */
&disasm_unknown, /* 0x1C */
&disasm_unknown, /* 0x1D */
&disasm_unknown, /* 0x1E */
&disasm_unknown, /* 0x1F */
&disasm_unknown, /* 0x20 */
&disasm_unknown, /* 0x21 */
&disasm_unknown, /* 0x22 */
&disasm_unknown, /* 0x23 */
&disasm_unknown, /* 0x24 */
&disasm_unknown, /* 0x25 */
&disasm_unknown, /* 0x26 */
&disasm_unknown, /* 0x27 */
&disasm_unknown, /* 0x28 */
&disasm_unknown, /* 0x29 */
&disasm_unknown, /* 0x2A */
&disasm_unknown, /* 0x2B */
&disasm_unknown, /* 0x2C */
&disasm_unknown, /* 0x2D */
&disasm_unknown, /* 0x2E */
&disasm_unknown, /* 0x2F */
&disasm_30, /* 0x30 */
&disasm_31, /* 0x31 */
&disasm_32, /* 0x32 */
&disasm_33, /* 0x33 */
&disasm_34, /* 0x34 */
&disasm_35, /* 0x35 */
&disasm_unknown, /* 0x36 */
&disasm_unknown, /* 0x37 */
&disasm_unknown, /* 0x38 */
&disasm_unknown, /* 0x39 */
&disasm_unknown, /* 0x3A */
&disasm_unknown, /* 0x3B */
&disasm_unknown, /* 0x3C */
&disasm_unknown, /* 0x3D */
&disasm_unknown, /* 0x3E */
&disasm_unknown, /* 0x3F */
&disasm_unknown, /* 0x40 */
&disasm_unknown, /* 0x41 */
&disasm_unknown, /* 0x42 */
&disasm_unknown, /* 0x43 */
&disasm_unknown, /* 0x44 */
&disasm_unknown, /* 0x45 */
&disasm_unknown, /* 0x46 */
&disasm_unknown, /* 0x47 */
&disasm_unknown, /* 0x48 */
&disasm_unknown, /* 0x49 */
&disasm_unknown, /* 0x4A */
&disasm_unknown, /* 0x4B */
&disasm_unknown, /* 0x4C */
&disasm_unknown, /* 0x4D */
&disasm_unknown, /* 0x4E */
&disasm_unknown, /* 0x4F */
&disasm_50, /* 0x50 */
&disasm_51, /* 0x51 */
&disasm_52, /* 0x52 */
&disasm_53, /* 0x53 */
&disasm_54, /* 0x54 */
&disasm_55, /* 0x55 */
&disasm_56, /* 0x56 */
&disasm_57, /* 0x57 */
&disasm_unknown, /* 0x58 */
&disasm_unknown, /* 0x59 */
&disasm_unknown, /* 0x5A */
&disasm_unknown, /* 0x5B */
&disasm_unknown, /* 0x5C */
&disasm_unknown, /* 0x5D */
&disasm_unknown, /* 0x5E */
&disasm_unknown, /* 0x5F */
&disasm_unknown, /* 0x60 */
&disasm_unknown, /* 0x61 */
&disasm_unknown, /* 0x62 */
&disasm_unknown, /* 0x63 */
&disasm_unknown, /* 0x64 */
&disasm_unknown, /* 0x65 */
&disasm_unknown, /* 0x66 */
&disasm_unknown, /* 0x67 */
&disasm_unknown, /* 0x68 */
&disasm_unknown, /* 0x69 */
&disasm_unknown, /* 0x6A */
&disasm_unknown, /* 0x6B */
&disasm_unknown, /* 0x6C */
&disasm_unknown, /* 0x6D */
&disasm_unknown, /* 0x6E */
&disasm_unknown, /* 0x6F */
&disasm_unknown, /* 0x70 */
&disasm_unknown, /* 0x71 */
&disasm_unknown, /* 0x72 */
&disasm_unknown, /* 0x73 */
&disasm_unknown, /* 0x74 */
&disasm_unknown, /* 0x75 */
&disasm_unknown, /* 0x76 */
&disasm_unknown, /* 0x77 */
&disasm_unknown, /* 0x78 */
&disasm_unknown, /* 0x79 */
&disasm_unknown, /* 0x7A */
&disasm_unknown, /* 0x7B */
&disasm_unknown, /* 0x7C */
&disasm_unknown, /* 0x7D */
&disasm_unknown, /* 0x7E */
&disasm_unknown, /* 0x7F */
&disasm_80, /* 0x80 */
&disasm_81, /* 0x81 */
&disasm_82, /* 0x82 */
&disasm_83, /* 0x83 */
&disasm_unknown, /* 0x84 */
&disasm_unknown, /* 0x85 */
&disasm_unknown, /* 0x86 */
&disasm_unknown, /* 0x87 */
&disasm_unknown, /* 0x88 */
&disasm_unknown, /* 0x89 */
&disasm_unknown, /* 0x8A */
&disasm_unknown, /* 0x8B */
&disasm_unknown, /* 0x8C */
&disasm_unknown, /* 0x8D */
&disasm_unknown, /* 0x8E */
&disasm_unknown, /* 0x8F */
&disasm_90, /* 0x90 */
&disasm_91, /* 0x91 */
&disasm_unknown, /* 0x92 */
&disasm_unknown, /* 0x93 */
&disasm_unknown, /* 0x94 */
&disasm_unknown, /* 0x95 */
&disasm_unknown, /* 0x96 */
&disasm_unknown, /* 0x97 */
&disasm_unknown, /* 0x98 */
&disasm_unknown, /* 0x99 */
&disasm_unknown, /* 0x9A */
&disasm_unknown, /* 0x9B */
&disasm_unknown, /* 0x9C */
&disasm_unknown, /* 0x9D */
&disasm_unknown, /* 0x9E */
&disasm_unknown, /* 0x9F */
&disasm_unknown, /* 0xA0 */
&disasm_unknown, /* 0xA1 */
&disasm_unknown, /* 0xA2 */
&disasm_unknown, /* 0xA3 */
&disasm_unknown, /* 0xA4 */
&disasm_unknown, /* 0xA5 */
&disasm_unknown, /* 0xA6 */
&disasm_unknown, /* 0xA7 */
&disasm_unknown, /* 0xA8 */
&disasm_unknown, /* 0xA9 */
&disasm_unknown, /* 0xAA */
&disasm_unknown, /* 0xAB */
&disasm_unknown, /* 0xAC */
&disasm_unknown, /* 0xAD */
&disasm_unknown, /* 0xAE */
&disasm_unknown, /* 0xAF */
&disasm_unknown, /* 0xB0 */
&disasm_unknown, /* 0xB1 */
&disasm_unknown, /* 0xB2 */
&disasm_unknown, /* 0xB3 */
&disasm_unknown, /* 0xB4 */
&disasm_unknown, /* 0xB5 */
&disasm_unknown, /* 0xB6 */
&disasm_unknown, /* 0xB7 */
&disasm_unknown, /* 0xB8 */
&disasm_unknown, /* 0xB9 */
&disasm_unknown, /* 0xBA */
&disasm_unknown, /* 0xBB */
&disasm_unknown, /* 0xBC */
&disasm_unknown, /* 0xBD */
&disasm_unknown, /* 0xBE */
&disasm_unknown, /* 0xBF */
&disasm_C0, /* 0xC0 */
&disasm_unknown, /* 0xC1 */
&disasm_unknown, /* 0xC2 */
&disasm_unknown, /* 0xC3 */
&disasm_unknown, /* 0xC4 */
&disasm_unknown, /* 0xC5 */
&disasm_unknown, /* 0xC6 */
&disasm_unknown, /* 0xC7 */
&disasm_unknown, /* 0xC8 */
&disasm_unknown, /* 0xC9 */
&disasm_unknown, /* 0xCA */
&disasm_unknown, /* 0xCB */
&disasm_unknown, /* 0xCC */
&disasm_unknown, /* 0xCD */
&disasm_unknown, /* 0xCE */
&disasm_unknown, /* 0xCF */
&disasm_unknown, /* 0xD0 */
&disasm_unknown, /* 0xD1 */
&disasm_unknown, /* 0xD2 */
&disasm_unknown, /* 0xD3 */
&disasm_unknown, /* 0xD4 */
&disasm_unknown, /* 0xD5 */
&disasm_unknown, /* 0xD6 */
&disasm_unknown, /* 0xD7 */
&disasm_unknown, /* 0xD8 */
&disasm_unknown, /* 0xD9 */
&disasm_unknown, /* 0xDA */
&disasm_unknown, /* 0xDB */
&disasm_unknown, /* 0xDC */
&disasm_unknown, /* 0xDD */
&disasm_unknown, /* 0xDE */
&disasm_unknown, /* 0xDF */
&disasm_unknown, /* 0xE0 */
&disasm_unknown, /* 0xE1 */
&disasm_unknown, /* 0xE2 */
&disasm_unknown, /* 0xE3 */
&disasm_unknown, /* 0xE4 */
&disasm_unknown, /* 0xE5 */
&disasm_unknown, /* 0xE6 */
&disasm_unknown, /* 0xE7 */
&disasm_unknown, /* 0xE8 */
&disasm_unknown, /* 0xE9 */
&disasm_unknown, /* 0xEA */
&disasm_unknown, /* 0xEB */
&disasm_unknown, /* 0xEC */
&disasm_unknown, /* 0xED */
&disasm_unknown, /* 0xEE */
&disasm_unknown, /* 0xEF */
&disasm_unknown, /* 0xF0 */
&disasm_unknown, /* 0xF1 */
&disasm_unknown, /* 0xF2 */
&disasm_unknown, /* 0xF3 */
&disasm_unknown, /* 0xF4 */
&disasm_unknown, /* 0xF5 */
&disasm_unknown, /* 0xF6 */
&disasm_unknown, /* 0xF7 */
&disasm_unknown, /* 0xF8 */
&disasm_unknown, /* 0xF9 */
&disasm_unknown, /* 0xFA */
&disasm_unknown, /* 0xFB */
&disasm_unknown, /* 0xFC */
&disasm_unknown, /* 0xFD */
&disasm_unknown, /* 0xFE */
&disasm_nop      /* 0xFF */
